In [1]:
import numpy as np
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [2]:
l = [[1,2,3],[4,5,6],[7,8,9]]
l
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
arr =np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
b = np.ones((4,4))
b

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [5]:
np.random.rand(10)

array([0.17277838, 0.87395083, 0.02669958, 0.47198695, 0.57940722,
       0.18564225, 0.92174112, 0.56223545, 0.65432141, 0.9185907 ])

In [6]:
np.random.randn(10)

array([ 0.14722819,  0.79452776,  1.05562844, -0.74028672,  0.23679189,
        0.38038516,  0.83227265, -0.983601  ,  1.11790036, -0.05407667])

In [7]:
np.random.randint(1,20,5)

array([12, 16, 11,  5, 14])

In [8]:
#Array attributes
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr
arr.shape
arr.size


9

In [9]:
np.sum(arr)
np.sum(arr,axis=0)

array([12, 15, 18])

In [10]:
arr = np.arange(1,21)
np.reshape(arr,(4,5))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [11]:
arr = np.arange(1,21)
arr
arr[4:10]

array([ 5,  6,  7,  8,  9, 10])

In [12]:
arr = np.arange(1,21).reshape(4,5)
arr


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [13]:
arr[2]
arr[2][3]
arr[1:3,0:2]
arr[1:4,2:4]
arr[:,3]

array([ 4,  9, 14, 19])

In [14]:
#Arithmetic operations
a1 = np.array([1,2,3,4,5,6])
a2 = np.array([7,8,9,10,11,12])
a1 + a2
a1 * a2

array([ 7, 16, 27, 40, 55, 72])

In [15]:
#Broadcasting
array = np.array([1,2,3,4,5])
array + 20

array([21, 22, 23, 24, 25])

In [16]:
#matrix mul
a1 = np.array([[1,2],[3,4]])
a2 = np.array([[5,6],[7,8]])

a1@ a2
np.dot(a1,a2)

array([[19, 22],
       [43, 50]])

In [17]:
#transpose 
a1.T

array([[1, 3],
       [2, 4]])

In [18]:
#stacking an array
a3 = np.array([1,2,3])
a4 = np.array([4,5,6])
np.vstack((a3,a4))
np.hstack((a3,a4))
np.column_stack((a3,a4))


array([[1, 4],
       [2, 5],
       [3, 6]])

In [19]:
#splitting array
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [20]:
np.vsplit(c,2)
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [21]:
h1 = np.array([[11,12],[13,14]])
h2 = np.array([[2,6],[17,18]])
h1 @ h2
h1 + h2

array([[13, 18],
       [30, 32]])